export default {
  INIT_APP_STATE: 'INIT_APP_STATE',
  PATCH_FAMILY: 'PATCH_FAMILY',
  FAMILY_FORM_OPEN: 'FAMILY_FORM_OPEN',
  UNIT_PRIORITY_CHANGE: 'UNIT_PRIORITY_CHANGE',
  RELEASE_PRIORITY: 'RELEASE_PRIORITY',
  IMPORT_FAMILY_DATA: 'IMPORT_FAMILY_DATA',
  OPEN_TAB_CHANGED: 'OPEN_TAB_CHANGED',
  SAVE_FULL_STATE: 'SAVE_FULL_STATE',
};
